version: '3.8'
services:
  client:
    container_name: react-app
    build:
      context: client
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80

  service:
    container_name: service
    build:
      context: service
    restart: always
    ports:
      - 8080:8080
    environment:
      SPRING_DATA_MONGODB_HOST: mongo6
    healthcheck:
      test: "exit 0"
    depends_on:
      - mongo6
  mongo6:
    image: mongo:6
    container_name: mongo6
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
#    volumes: #
#      - $HOME/mongo:/data/db
    healthcheck:
      test: "exit 0"
